name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: crystal docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
